export const personalInfo = {
  name: "Madhukumar Gowroju",
  title: "Data Analyst | Power BI Developer",
  email: "gmadhukumar389@gmail.com",
  phone: "8096004740",
  location: "India",
  summary:
    "Results-driven Data Analyst and Power BI Developer with 4+ years of experience at Tata Consultancy Services. Specializing in building high-performance dashboards, complex DAX calculations, data modeling, and SQL optimization. Passionate about transforming raw data into actionable business intelligence that drives strategic decision-making.",
};

export const experience = [
  {
    company: "Tata Consultancy Services (TCS)",
    role: "Data Analyst | Power BI Developer",
    period: "May 2022 - Present",
    achievements: [
      "Delivered 30% improvement in report performance by optimizing Power BI data models, reducing unnecessary columns, and improving query efficiency.",
      "Accelerated dashboard refresh times by 50% by converting complex manual Excel/SQL reporting into optimized SQL queries and Power BI transformations.",
      "Reduced manual reporting effort by 30% by implementing automated Power BI datasets, scheduled refresh, and reusable report templates.",
      "Improved data availability and business reporting speed by 25% by building real-time/near real-time reporting pipelines using SQL and Power BI refresh automation.",
      "Automated KPI monitoring and report distribution using Power BI Service eliminating manual checks and saving over 5 hours per week.",
    ],
  },
];

export const projects = [
  {
    title: "Tata Teleservices - BI",
    description:
      "End-to-end Power BI implementation for telecom business intelligence, connecting multiple data sources and building comprehensive KPI dashboards.",
    details: [
      "Connected Power BI to multiple data sources such as SQL databases, Excel, and flat files for real-time and scheduled reporting.",
      "Performed data transformation and cleaning using Power Query (M language) to prepare structured datasets for analysis.",
      "Created advanced calculations using DAX including measures for KPIs, time intelligence, and aggregations.",
      "Built business KPIs like SLA, Orders, Customer churn rate, ARPU and visualizations like bar charts, line graphs, slicers, and drill-through reports.",
      "Implemented row-level security (RLS) to restrict data access based on user roles.",
      "Optimized report performance by reducing data load, using proper data types, and minimizing unnecessary visuals.",
      "Published and shared reports via Power BI Service, enabling collaboration and scheduled data refresh.",
    ],
  },
  {
    title: "Tata Teleservices - Order Management using SQL",
    description:
      "Complex SQL development for order management analytics, handling large-scale data extraction, transformation, and analysis.",
    details: [
      "Wrote complex SQL queries using JOINs, subqueries, and CTEs to extract, transform, and analyze large datasets from relational databases.",
      "Utilized window functions such as ROW_NUMBER(), RANK(), and LAG() for advanced analytics like ranking, trend analysis, and deduplication.",
      "Performed data cleaning and transformation by handling null values, duplicates, and inconsistent data using functions like COALESCE, CASE, and CAST.",
      "Designed and optimized queries using indexes and execution plans, improving query performance and reducing runtime for large datasets.",
      "Built aggregated datasets using GROUP BY, HAVING, and conditional aggregation to support business reporting and dashboards.",
      "Worked with date functions and time-based analysis (monthly, quarterly trends) for reporting and forecasting.",
      "Validated and reconciled data between multiple sources to ensure data accuracy and consistency.",
      "Collaborated with cross-functional teams to convert business requirements into data-driven solutions using SQL.",
    ],
  },
];

export const skills = {
  powerBI: [
    { name: "Power BI Desktop", level: 95 },
    { name: "DAX", level: 92 },
    { name: "Power Query (M Language)", level: 90 },
    { name: "Data Modelling", level: 88 },
    { name: "Row-Level Security (RLS)", level: 85 },
    { name: "Power BI Service", level: 90 },
    { name: "Dashboard Design", level: 92 },
    { name: "Performance Optimization", level: 87 },
  ],
  sql: [
    { name: "Complex JOINs & Subqueries", level: 92 },
    { name: "CTEs & Window Functions", level: 90 },
    { name: "Query Optimization", level: 88 },
    { name: "Aggregate Functions", level: 95 },
    { name: "Data Cleaning & Transformation", level: 90 },
    { name: "Stored Procedures", level: 82 },
  ],
  other: [
    { name: "Data Visualization", level: 92 },
    { name: "ETL Processes", level: 85 },
    { name: "Excel Advanced", level: 88 },
    { name: "Business Intelligence", level: 90 },
    { name: "Requirement Analysis", level: 85 },
    { name: "Cross-functional Collaboration", level: 88 },
  ],
};

export const certifications = [
  {
    title: "Microsoft Certified: Power BI Data Analyst Associate",
    issuer: "Microsoft",
    description: "Validated expertise in Power BI data modeling, visualization, and analytics.",
  },
  {
    title: "Microsoft Certified: Azure Data Fundamentals",
    issuer: "Microsoft",
    description: "Foundation-level understanding of core data concepts and Azure data services.",
  },
];

export const achievements = [
  "30% improvement in Power BI report performance through data model optimization",
  "50% faster dashboard refresh by converting manual Excel/SQL to automated workflows",
  "30% reduction in manual reporting effort via automated datasets and templates",
  "25% faster data availability through real-time reporting pipeline automation",
  "5+ hours saved weekly by automating KPI monitoring and report distribution",
];

export const education = [
  {
    degree: "Bachelor of Technology in Mechanical Engineering",
    institution: "GEC - JNTUK",
    year: "2021",
    gpa: "7.89",
  },
];

export const courseData = {
  powerBI: [
    {
      id: 1,
      title: "Data Analytics & Business Foundations",
      description: "Core concepts of data analytics, business intelligence, and the role of data-driven decision making.",
      topics: [
        "Understanding Business Intelligence and its evolution",
        "Data Analytics lifecycle: from raw data to insights",
        "Key business metrics and KPI frameworks",
        "Data governance and data quality fundamentals",
        "Stakeholder requirement gathering and analysis",
        "Introduction to data warehousing concepts",
        "OLAP vs OLTP systems explained",
        "Data storytelling and visualization best practices",
      ],
    },
    {
      id: 2,
      title: "Introduction to Power BI",
      description: "Getting started with Power BI ecosystem, installation, and navigating the interface.",
      topics: [
        "Power BI ecosystem overview: Desktop, Service, Mobile, Gateway",
        "Installing and configuring Power BI Desktop",
        "Navigating the Power BI interface and workspaces",
        "Understanding Power BI licensing and capacity planning",
        "Connecting to first data source",
        "Building first visual: end-to-end walkthrough",
        "Power BI file types: PBIX, PBIT, PBIDS",
        "Best practices for Power BI project setup",
      ],
    },
    {
      id: 3,
      title: "Power BI Desktop & Power Query",
      description: "Deep dive into Power Query for data transformation and cleansing using the M language.",
      topics: [
        "Power Query Editor interface and navigation",
        "Connecting to diverse data sources (SQL, Excel, CSV, Web, APIs)",
        "Data transformation techniques: pivot, unpivot, merge, append",
        "M Language fundamentals for custom transformations",
        "Parameterized queries for dynamic data loading",
        "Error handling and data quality checks in Power Query",
        "Query dependencies and performance profiling",
        "Creating reusable Power Query templates",
      ],
    },
    {
      id: 4,
      title: "Data Modelling",
      description: "Building robust data models with relationships, star schemas, and best practices.",
      topics: [
        "Star schema vs Snowflake schema design patterns",
        "Creating and managing table relationships",
        "Fact tables vs Dimension tables",
        "Active vs Inactive relationships and USERELATIONSHIP",
        "Role-playing dimensions and date tables",
        "Bi-directional cross-filtering: when and how to use",
        "Calculated columns vs Measures: performance considerations",
        "Data model optimization techniques",
      ],
    },
    {
      id: 5,
      title: "DAX (Data Analysis Expressions)",
      description: "Master DAX for advanced calculations, time intelligence, and complex business logic.",
      topics: [
        "DAX fundamentals: syntax, context (row vs filter), evaluation",
        "CALCULATE and CALCULATETABLE: the most powerful DAX functions",
        "Time intelligence: YTD, QTD, MTD, same-period-last-year, moving averages",
        "FILTER, ALL, ALLEXCEPT, and context modification techniques",
        "Ranking and segmentation using RANKX and TOPN",
        "Advanced DAX patterns: semi-additive measures, ABC analysis",
        "Performance optimization: avoiding slow DAX patterns",
        "Debugging and testing DAX with EVALUATE and tabular output",
      ],
    },
    {
      id: 6,
      title: "Data Visualization",
      description: "Designing impactful, user-friendly dashboards with best-practice visualization techniques.",
      topics: [
        "Visualization best practices and cognitive load principles",
        "Custom visuals from AppSource and certified visuals",
        "Building interactive dashboards with slicers, filters, and drill-through",
        "Bookmarks, buttons, and navigation for storytelling",
        "Conditional formatting and dynamic formatting rules",
        "Custom tooltips and report page tooltips",
        "Analytics pane: trend lines, forecasts, clusters, reference lines",
        "Accessibility in Power BI reports (accessibility standards)",
      ],
    },
    {
      id: 7,
      title: "Advanced Transformation",
      description: "Advanced Power Query techniques for complex data scenarios.",
      topics: [
        "Custom connectors and API integration with Power Query",
        "Web scraping and dynamic data extraction",
        "Advanced M: custom functions, lists, and records",
        "Incremental refresh for large datasets",
        "Dataflows: centralized data preparation",
        "DirectQuery vs Import vs Composite models",
        "Handling slowly changing dimensions (SCD)",
        "Performance monitoring with Power Query Diagnostics",
      ],
    },
    {
      id: 8,
      title: "Performance Optimization",
      description: "Techniques to optimize Power BI reports for speed, efficiency, and scalability.",
      topics: [
        "VertiPaq engine architecture and compression",
        "Reducing model size: removing unnecessary columns and rows",
        "Optimizing DAX for performance",
        "Query folding and its importance",
        "Storage mode: Dual, Import, and DirectQuery optimization",
        "Best practices for large datasets (>1M rows)",
        "Performance Analyzer: identifying bottlenecks",
        "Aggregation tables for pre-summarized data",
      ],
    },
    {
      id: 9,
      title: "Power BI Service",
      description: "Publishing, sharing, and managing reports in the Power BI cloud service.",
      topics: [
        "Publishing reports from Desktop to Power BI Service",
        "Workspaces: creation, roles, and permissions",
        "Dashboards vs Reports vs Apps in Power BI Service",
        "Scheduled refresh configuration and gateway setup",
        "Power BI metrics and usage analytics",
        "Exploring data with Q&A natural language queries",
        "Exporting and sharing options (secure embedding)",
        "Power BI Service administration and monitoring",
      ],
    },
    {
      id: 10,
      title: "Deployment & Environments",
      description: "Managing deployment pipelines, CI/CD, and environment strategies.",
      topics: [
        "Power BI Deployment Pipelines: Dev, Test, Production",
        "Managing deployment rules and configuration",
        "CI/CD integration with Azure DevOps and GitHub",
        "Version control for Power BI projects",
        "Environment strategy: isolating development and production",
        "Change management and deployment approval workflows",
        "Backup and recovery strategies for Power BI",
        "Automated deployment with PowerShell and REST APIs",
      ],
    },
    {
      id: 11,
      title: "Security & Governance",
      description: "Implementing security, compliance, and governance for Power BI enterprise deployments.",
      topics: [
        "Row-Level Security (RLS): static vs dynamic",
        "Object-Level Security (OLS) for sensitive measures",
        "Power BI data classification and sensitivity labels",
        "Microsoft Purview integration for data governance",
        "Audit logs and activity monitoring in Power BI",
        "Compliance standards: GDPR, HIPAA, SOC2 considerations",
        "Managing external user access with Azure B2B",
        "Security best practices for data sources and gateways",
      ],
    },
    {
      id: 12,
      title: "Dashboards",
      description: "Designing executive-level dashboards for strategic decision making.",
      topics: [
        "Executive dashboard design principles",
        "Real-time dashboards with streaming datasets",
        "Mobile-optimized dashboard layouts",
        "Dashboard alerts and data-driven notifications",
        "Custom themes and corporate branding",
        "Multi-page report navigation with bookmark navigation",
        "Dashboard performance monitoring",
        "Best practices for KPI scorecards",
      ],
    },
    {
      id: 13,
      title: "Integrations",
      description: "Integrating Power BI with other Microsoft and third-party tools.",
      topics: [
        "Power BI and Excel integration (Analyze in Excel)",
        "Power BI with Azure Synapse Analytics and Databricks",
        "Embedding Power BI in custom applications (Power BI Embedded)",
        "Power BI REST API for automation",
        "Power BI with Microsoft Teams and SharePoint",
        "Azure Analysis Services integration",
        "Power BI with Python and R scripts",
        "Third-party data connectors and custom connectors",
      ],
    },
    {
      id: 14,
      title: "Power Platform & AI",
      description: "Leveraging AI capabilities and Power Platform integration for advanced analytics.",
      topics: [
        "Power BI and Power Apps integration",
        "Power Automate workflows for data-driven automation",
        "Power BI with Azure Machine Learning models",
        "AI visuals: Q&A, Key Influencers, Decomposition Tree",
        "Cognitive Services integration (text, image analytics)",
        "AutoML in Power BI for predictive analytics",
        "Copilot in Power BI and AI-assisted data preparation",
        "Building data apps with Power Platform and Power BI",
      ],
    },
  ],
  sql: [
    {
      id: 1,
      title: "Introduction to Data Warehouse & Database",
      description: "Foundations of data warehousing, relational databases, and SQL environments.",
      topics: [
        "Relational database fundamentals: tables, rows, columns, keys",
        "Data warehouse architecture: staging, warehouse, mart layers",
        "OLTP vs OLAP: when to use each",
        "Normalization vs Denormalization strategies",
        "Database design principles and entity relationships",
        "Primary keys, foreign keys, and indexing basics",
        "SQL Server, MySQL, PostgreSQL: platform differences",
        "Setting up SQL environment for practice",
      ],
    },
    {
      id: 2,
      title: "Introduction to SQL",
      description: "Getting started with SQL syntax, queries, and the SELECT statement.",
      topics: [
        "SQL language categories: DDL, DML, DCL, TCL",
        "SELECT statement: retrieving data from tables",
        "WHERE clause: filtering with AND, OR, IN, BETWEEN, LIKE",
        "ORDER BY, DISTINCT, and TOP/LIMIT clauses",
        "Using NULL in SQL and COALESCE/ISNULL functions",
        "String functions: CONCAT, SUBSTRING, REPLACE, LEN",
        "Date functions: DATEADD, DATEDIFF, FORMAT, GETDATE",
        "CASE statements for conditional logic",
      ],
    },
    {
      id: 3,
      title: "DDL & DML Statements",
      description: "Data Definition Language and Data Manipulation Language in depth.",
      topics: [
        "CREATE, ALTER, DROP: managing database objects",
        "Table creation with constraints (PK, FK, UNIQUE, CHECK, DEFAULT)",
        "INSERT, UPDATE, DELETE: modifying data",
        "Transactions: COMMIT, ROLLBACK, SAVEPOINT",
        "TRUNCATE vs DELETE: performance and behavior",
        "Views: creating and managing virtual tables",
        "Indexes: clustered, non-clustered, and covering indexes",
        "Stored procedures and functions basics",
      ],
    },
    {
      id: 4,
      title: "Aggregate Functions",
      description: "Using aggregate functions and GROUP BY for data summarization.",
      topics: [
        "COUNT, SUM, AVG, MIN, MAX: core aggregate functions",
        "GROUP BY: grouping data for summary analysis",
        "HAVING clause: filtering grouped data",
        "DISTINCT vs COUNT(DISTINCT) for unique values",
        "ROLLUP and CUBE for multi-level aggregation",
        "GROUPING SETS for custom aggregation hierarchies",
        "Statistical functions: STDEV, VAR, PERCENTILE",
        "Window aggregate functions with OVER() clause",
      ],
    },
    {
      id: 5,
      title: "Joins",
      description: "Mastering SQL JOINs for combining data across multiple tables.",
      topics: [
        "INNER JOIN: matching records between tables",
        "LEFT, RIGHT, FULL OUTER JOIN: understanding outer joins",
        "CROSS JOIN: cartesian products and use cases",
        "SELF JOIN: joining a table to itself",
        "Multiple joins: joining 3+ tables in a single query",
        "Join conditions with AND, OR, and complex logic",
        "Performance implications of different join types",
        "INNER JOIN vs EXISTS vs IN: performance comparison",
      ],
    },
    {
      id: 6,
      title: "Set Operations",
      description: "Combining query results using UNION, INTERSECT, and EXCEPT operators.",
      topics: [
        "UNION and UNION ALL: combining result sets",
        "INTERSECT: finding common records",
        "EXCEPT/MINUS: finding differences between sets",
        "Set operation rules: column count, data types, ordering",
        "Combining set operations with JOINs",
        "Practical use cases: data reconciliation, reporting",
        "Performance considerations for set operations",
        "Alternatives to set operations using JOINs",
      ],
    },
  ],
};

export const navLinks = [
  { label: "Home", href: "#home" },
  { label: "About", href: "#about" },
  { label: "Experience", href: "#experience" },
  { label: "Skills", href: "#skills" },
  { label: "Projects", href: "#projects" },
  { label: "Contact", href: "#contact" },
];
